apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tenant-service-internal
  description: Internal Tenant Service
  tags:
    - typescript
    - tenant-service
    - apigateway
    - service
    - restful
    - backend
spec:
  type: service
  lifecycle: experimental
  owner: engineering
  system: shared
  dependsOn: ['resource:tenant-configuration-dynamodb-table']
  providesApis:
    - api:default/tenant-service-internal-api
  apiProvides: ['tenant-service-internal-api']
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tenant-service-internal-api
  description: Tenant Service Internal API
spec:
  type: openapi
  lifecycle: production
  owner: architecture@example.com
  definition:
    $text: ./api-spec.json