apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tenant-service-internal
  description: Internal Tenant Service
  tags:
    - typescript
    - tenant-service
    - apigateway
    - service
    - restful
    - backend
spec:
  type: service
  lifecycle: experimental
  owner: engineering
  system: shared
  dependsOn:
    - resource:default/tenant-configuration-dynamodb-table
    - resource:default/token-cache-dynamodb-table
  providesApis:
    - api:default/tenant-service-internal-api
  apiProvides: ['tenant-service-internal-api']

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tenant-configuration-dynamodb-table
  description: DynamoDB table for tenant configurations
spec:
  type: database
  owner: engineering
  system: shared

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: token-cache-dynamodb-table
  description: DynamoDB table for token cache
spec:
  type: database
  owner: engineering
  system: shared
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tenant-service-internal-api
  description: Tenant Service Internal API
spec:
  type: openapi
  lifecycle: production
  owner: architecture@example.com
  definition:
    $text: ./api-spec.json